apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "coronarki.fullname" . }}
  labels:
    {{- include "coronarki.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "coronarki.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "coronarki.selectorLabels" . | nindent 8 }}
      annotations:
        app.ts: {{ date "20060102150405" .Release.Time | quote }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: app
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: INFLUXDB_HOST
            value: {{ ternary (printf "%s-influxdb" .Release.Namespace) .Values.influxdb.service.name .Values.influxdb.enabled | quote}}
          - name: INFLUXDB_PORT
            value: {{ .Values.influxdb.service.port | quote}}
          - name: INFLUXDB_DATABASE
            value: {{ .Values.influxdb.database | quote }}
          - name: INFLUXDB_USER
            value: {{ .Values.influxdb.user.name | quote }}
          - name: INFLUXDB_PASSWORD
            value: {{ .Values.influxdb.user.pwd | quote }}
          command:
          - "/usr/local/bin/php"
          - "/app/import.php"
          - "daemon"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
