{{- if .Values.grafana.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "coronarki.fullname" . }}-grafana-datasource
  labels:
    {{- include "coronarki.labels" . | nindent 4 }}
data:
  datasources.yaml: {{ tpl (.Files.Get "grafana/datasources.yaml") . | b64enc }}
{{- end -}}